### ISSUE TITLE
I have added the templates but branches have diverged

### ISSUE THREAD

**Issue by gbozee** [tsolarin/pyconng#1]
hello. I have added a template and set up all the third party templates using the fork from djangocon as a baseline. Currently I can't merge because your branch and mine are currently diverged. Could you please create a new branch that doesn't consist of any code so that that way I can merge my changes with yours.

**Comment by tsolarin** [comment]
@gbozee did you base your code off master? Why not just open a pull request?

**Comment by gbozee** [comment]
I can't I already tried that. Would do so again later today.

**Comment by gbozee** [comment]
![screenshot from 2016-08-27 00 21 02](https://cloud.githubusercontent.com/assets/1777544/18023040/4447d914-6bec-11e6-84b7-e59d9519e894.png)

This is exactly the issue I was telling you about when trying to issue a pull request. My fork is seriously diverged from yours. You would need to create a new branch that doesn't have any code so that I can issue a pull request on that branch and not your master branch.

![screenshot from 2016-08-27 00 23 56](https://cloud.githubusercontent.com/assets/1777544/18023068/992d59e0-6bec-11e6-8a41-67e19d9b4f2a.png)

Issuing a pull request currently to your master branch doesn't seem to work. The image above is my current fork. I changed the folder structure.

**Comment by tsolarin** [comment]
@gbozee I've created a new branch called `empty` feel free to open a PR against that

**Comment by gbozee** [comment]
Alright. Would Issue the pull request now
